---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-eso
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 3745fd94-b05c-4720-9d0f-fc97e76d4850
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-eso.sh"
        post_validation: "tests/scripts/post-validation-eso.sh"
