# More info about this file at https://github.com/terraform-ibm-modules/common-pipeline-assets/blob/main/.github/workflows/terraform-test-pipeline.md#cra-config-yaml
version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "examples/all-combined"
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json"
    CRA_ENVIRONMENT_VARIABLES:  # An optional map of environment variables for CRA, where the key is the variable name and value is the value. Useful for providing TF_VARs.
      TF_VAR_existing_cis_instance_name: "test_value_for_cis_instance_name"
      TF_VAR_existing_cis_instance_resource_group_id:  "test_value_for_cis_instance_rg_id"
      TF_VAR_existing_sdnlb_serviceid_name:  "test_value_for_existing_sdnlb_serviceid_name"
